const items = [
  {
    kategori: "All",
    items: [
      {
        id: 1,
        nama: "ÄLVSTA",
        harga: 1195000,
        deskripsi: "Kursi, buatan tangan rotan/sefast putih.",
        image: "https://d2xjmi1k71iy2m.cloudfront.net/dairyfarm/id/images/157/1115725_PE872233_S4.webp",
        kategori: "Furniture",
      },
      {
        id: 2,
        nama: "BALTSAR",
        harga: 2995000,
        deskripsi: "Nyaman untuk diduduki berkat dudukan yang berbentuk mangkuk dan sandaran punggung berbentuk bulat. Mudah dirakit tanpa alat atau sekrup.",
        image: "https://d2xjmi1k71iy2m.cloudfront.net/dairyfarm/id/images/848/1184815_PE898079_S4.webp",
        kategori: "Furniture",
      },
      {
        id: 3,
        nama: "ADDE",
        harga: 180000,
        deskripsi: "Kursi sofa empuk yang nyaman untuk duduk.",
        image: "https://d2xjmi1k71iy2m.cloudfront.net/dairyfarm/id/images/282/0728279_PE736175_S5.webp",
        kategori: "Furniture",
      },
      {
        id: 4,
        nama: "VIHALS",
        harga: 2799000,
        deskripsi: "Gunakan di seluruh rumah, sebagai mandiri atau dengan perabot VIHALS lainnya. Kedalaman 37 cm berarti bufet mudah dipasang bahkan di ruang sempit, seperti lorong atau ruang makan yang lebih kecil.",
        image: "https://d2xjmi1k71iy2m.cloudfront.net/dairyfarm/id/images/355/1035578_PE838113_S4.webp",
        kategori: "Furniture",
      },
      {
        id: 5,
        nama: "MICKE",
        harga: 1799000,
        deskripsi: "Meja kerja dengan desain minimalis.",
        image: "https://d2xjmi1k71iy2m.cloudfront.net/dairyfarm/id/images/360/0736018_PE740345_S4.webp",
        kategori: "Workspace",
      },
      {
        id: 6,
        nama: "IDÅSEN",
        harga: 4999000,
        deskripsi: "Kursi santai bulat yang cocok untuk ruang tamu.",
        image: "https://d2xjmi1k71iy2m.cloudfront.net/dairyfarm/id/images/136/0613638_PE686433_S4.webp",
        kategori: "Workspace",
      },
      {
        id: 7,
        nama: "BEKANT",
        harga: 4299000,
        deskripsi: "Lemari TV kayu jati dengan tampilan klasik.",
        image: "https://d2xjmi1k71iy2m.cloudfront.net/dairyfarm/id/images/443/0644320_PE702593_S4.webp",
        kategori: "Workspace",
      },
      {
        id: 8,
        nama: "TROTTEN",
        harga: 2999000,
        deskripsi: "Meja belajar anak dengan warna cerah dan menyenangkan.",
        image: "https://d2xjmi1k71iy2m.cloudfront.net/dairyfarm/id/images/207/1020759_PE831985_S4.webp",
        kategori: "Workspace",
      },
      {
        id: 9,
        nama: "RÅSHULT",
        harga: 499000,
        deskripsi: "Kursi lipat portabel yang mudah dibawa ke mana saja.",
        image: "https://d2xjmi1k71iy2m.cloudfront.net/dairyfarm/id/images/426/0742637_PE742749_S4.webp",
        kategori: "Accessories",
      },
      {
        id: 10,
        nama: "KUNGSFORS",
        harga: 2999000,
        deskripsi: "Lemari buku minimalis dengan rak penyimpanan yang praktis.",
        image: "https://d2xjmi1k71iy2m.cloudfront.net/dairyfarm/id/images/368/0736866_PE740781_S4.jpg",
        kategori: "Accessories",
      },
    ],
  },
  {
    kategori: "Furniture",
    items: [
      {
        id: 1,
        nama: "ÄLVSTA",
        harga: 1195000,
        deskripsi: "Kursi, buatan tangan rotan/sefast putih.",
        image: "https://d2xjmi1k71iy2m.cloudfront.net/dairyfarm/id/images/157/1115725_PE872233_S4.webp",
        kategori: "Furniture",
      },
      {
        id: 2,
        nama: "BALTSAR",
        harga: 2995000,
        deskripsi: "Nyaman untuk diduduki berkat dudukan yang berbentuk mangkuk dan sandaran punggung berbentuk bulat. Mudah dirakit tanpa alat atau sekrup.",
        image: "https://d2xjmi1k71iy2m.cloudfront.net/dairyfarm/id/images/848/1184815_PE898079_S4.webp",
        kategori: "Furniture",
      },
      {
        id: 3,
        nama: "ADDE",
        harga: 180000,
        deskripsi: "Kursi sofa empuk yang nyaman untuk duduk.",
        image: "https://d2xjmi1k71iy2m.cloudfront.net/dairyfarm/id/images/282/0728279_PE736175_S5.webp",
        kategori: "Furniture",
      },
      {
        id: 4,
        nama: "VIHALS",
        harga: 2799000,
        deskripsi: "Gunakan di seluruh rumah, sebagai mandiri atau dengan perabot VIHALS lainnya. Kedalaman 37 cm berarti bufet mudah dipasang bahkan di ruang sempit, seperti lorong atau ruang makan yang lebih kecil.",
        image: "https://d2xjmi1k71iy2m.cloudfront.net/dairyfarm/id/images/355/1035578_PE838113_S4.webp",
        kategori: "Furniture",
      },
    ],
  },
  {
    kategori: "Workspace",
    items: [
      {
        id: 5,
        nama: "MICKE",
        harga: 1799000,
        deskripsi: "Meja kerja dengan desain minimalis.",
        image: "https://d2xjmi1k71iy2m.cloudfront.net/dairyfarm/id/images/360/0736018_PE740345_S4.webp",
        kategori: "Workspace",
      },
      {
        id: 6,
        nama: "IDÅSEN",
        harga: 4999000,
        deskripsi: "Kursi santai bulat yang cocok untuk ruang tamu.",
        image: "https://d2xjmi1k71iy2m.cloudfront.net/dairyfarm/id/images/136/0613638_PE686433_S4.webp",
        kategori: "Workspace",
      },
      {
        id: 7,
        nama: "BEKANT",
        harga: 4299000,
        deskripsi: "Lemari TV kayu jati dengan tampilan klasik.",
        image: "https://d2xjmi1k71iy2m.cloudfront.net/dairyfarm/id/images/443/0644320_PE702593_S4.webp",
        kategori: "Workspace",
      },
      {
        id: 8,
        nama: "TROTTEN",
        harga: 2999000,
        deskripsi: "Meja belajar anak dengan warna cerah dan menyenangkan.",
        image: "https://d2xjmi1k71iy2m.cloudfront.net/dairyfarm/id/images/207/1020759_PE831985_S4.webp",
        kategori: "Workspace",
      },
    ],
  },
  {
    kategori: "Accessories",
    items: [
      {
        id: 9,
        nama: "RÅSHULT",
        harga: 499000,
        deskripsi: "Kursi lipat portabel yang mudah dibawa ke mana saja.",
        image: "https://d2xjmi1k71iy2m.cloudfront.net/dairyfarm/id/images/426/0742637_PE742749_S4.webp",
        kategori: "Accessories",
      },
      {
        id: 10,
        nama: "KUNGSFORS",
        harga: 2999000,
        deskripsi: "Lemari buku minimalis dengan rak penyimpanan yang praktis.",
        image: "https://d2xjmi1k71iy2m.cloudfront.net/dairyfarm/id/images/368/0736866_PE740781_S4.jpg",
        kategori: "Accessories",
      },
    ],
  },
];

export default items;
